M48
; DRILL file {KiCad 9.0.0} date 2025-08-18T13:42:09+0300
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-08-18T13:42:09+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C1.800
%
G90
G05
T1
X125.905Y-71.71
X125.905Y-77.49
T2
X124.5Y-88.2
T3
X129.0Y-88.2
M30
