M48
; DRILL file {KiCad 9.0.0} date 2025-08-24T13:48:56+0300
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-08-24T13:48:56+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0630
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0709
%
G90
G05
T1
X0.2679Y2.4543
X0.2679Y2.2268
T2
X0.2126Y1.8051
T3
X0.3898Y1.8051
M30
